name: Node CI

on:
  push:
  pull_request:

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x] # Обновлено для поддержки fs/promises

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Generate coverage report
        run: npm run coverage # Убедитесь, что скрипт "coverage" определен в вашем package.json

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage # Используйте команду, определенную в package.json
          debug: true
