name: CodeClimate Analysis

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Install codeclimate-test-reporter
        run: npm install -g codeclimate-test-reporter

      - name: Run CodeClimate Analysis
        run: |
          codeclimate-test-reporter format-coverage --input-type lcov coverage/lcov.info | codeclimate-test-reporter upload-coverage

      - name: Run tests
        run: npm test

      - name: Generate coverage report
        run: npm run coverage

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          debug: true
